# Generated by Django 2.2.4 on 2021-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211006_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='profile_pics'),
        ),
    ]
