# Generated by Django 2.2.7 on 2019-12-04 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('song', models.FileField(upload_to='musics/')),
                ('fav', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('lyrics', models.TextField(default='Unknown lyrics')),
                ('genre', models.CharField(choices=[('RK', 'Rock'), ('HIHO', 'Hip Hop'), ('J', 'Jazz'), ('C', 'Country'), ('B', 'Blues'), ('P', 'Pop'), ('S', 'Soul'), ('M', 'Metal'), ('D', 'Disco'), ('CL', 'Classical'), ('E', 'Electrodance'), ('R', 'Rap'), ('IP', 'Indie Pop'), ('K', 'K-Pop'), ('EM', 'Emo'), ('O', 'Opera')], default='', max_length=2)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, null=True, to='core.Music')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, null=True, to='core.Music')),
            ],
        ),
    ]
