# Generated by Django 3.0.3 on 2020-07-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('RK', 'Rock'), ('HIHO', 'Hip Hop'), ('J', 'Jazz'), ('C', 'Country'), ('B', 'Blues'), ('P', 'Pop'), ('S', 'Soul'), ('M', 'Metal'), ('D', 'Disco'), ('CL', 'Classical'), ('E', 'Electrodance'), ('R', 'Rap'), ('IP', 'Indie Pop'), ('K', 'K-Pop'), ('EM', 'Emo'), ('O', 'Opera')], default='', max_length=300),
        ),
    ]
